# Generated by Django 5.2.17 on 2026-09-20 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=24)),
                ('identity', models.CharField(max_length=72, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField()),
                ('mistakes', models.PositiveIntegerField()),
                ('ranked', models.BooleanField(default=True)),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='ranking_app.player')),
            ],
            options={
                'ordering': ['-score', 'mistakes', 'finished_at', 'id'],
            },
        ),
    ]
