# Generated by Django 5.2.17 on 2026-09-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='phase',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
